### PR TITLE
Liberal bitwidth assignment mode by default on precision initialization

### PR DESCRIPTION
**Pull request by ljaljushkin**
should be merged after #191 and #232

### CODE REVIEW

**Comment by ljaljushkin** [comment]
Jenkins please retry a build

**Comment by ljaljushkin** [comment]
Jenkins please retry a build

**Comment by ljaljushkin** [comment]
Jenkins please retry a build

**Comment by ljaljushkin** [comment]
should be merged after #191

**Comment by ljaljushkin** [comment]
@vshampor @asenina please review

**Review by vshampor — APPROVED** [review]

**Pull request merged**
