### PR TITLE
Unified tests for samples and refactored compression training tests

### PR DESCRIPTION
**Pull request by ljaljushkin**
### Changes

All sanity tests and nightly compression training tests use common machinery for sample validation.
Simplified `SampleTestDescriptor` by extracting sample specifics to `SampleHandler` classes and by moving validation specifics to `SampleValidator` classes.

### Reason for changes

Hard to maintain and extend sanity and nightly tests, which is required in search part of NAS (https://github.com/ljaljushkin/nncf_pytorch/pull/7)

### Related tickets

81789

### Tests
- sanity tests in the precommit scope
- [x] compression_training tests (build 76)

### CODE REVIEW

**Comment by ljaljushkin** [comment]
Jenkins please keep last build

**Comment by ljaljushkin** [comment]
Jenkins please stop all builds

**Comment by ljaljushkin** [comment]
Jenkins please stop all builds

**Comment by ljaljushkin** [comment]
Jenkins please retry a build

**Comment by ljaljushkin** [comment]
Jenkins please retry a build

**Comment by ljaljushkin** [comment]
There are 2 types of affected tests: sanity and compression training ones.
Sanity tests are passing in pre-commit CI. Compression training was manually launched for this PR (build 76). Tests are passing.

@vshampor, Please merge if there's no objection.

**Review by vshampor — APPROVED** [review]

**Pull request merged**
