### PR TITLE
API documentation cleanup

### PR DESCRIPTION
**Pull request by vshampor**
### Changes
Missing API entities were marked as such to make the documentation consistent; docstrings were formatted for correct rendering to HTML.

### Reason for changes
Better user-facing documentation.

### Related tickets
N/A

### Tests
N/A

### CODE REVIEW

**Review by alexsu52 — COMMENTED** [review]
Great staff! Could you please provide a link where I can view the generated documentation.

**Comment by vshampor** [comment]
I pushed the state here to my fork's GH pages, so you can see `https://vshampor.github.io/nncf` if you don't want to download the build artifacts from the API changes check action.

**Review by alexsu52 — COMMENTED** [review]
Some general comments from my side:
- Are you going to use some sphinix's theme or color scheme aligned with OpenVINO in the API documentation.
- Looks like the header "OpenVINO Neural Network Compression Framework" should be added.
- The titile doesn't look very pretty. May be rename to OpenVINO NNCF v2.4.0
image
- Surprisingly, classes and functions are in subpackages and we don't see them in the list.
image
 
https://vshampor.github.io/nncf/autoapi/nncf/index.html

**Comment by vshampor** [comment]
@alexsu52 I switched to the Furo theme which seems to do what you expect from the contents bar without me spending effort on learning Jinja templating. I also removed the version altogether because we will probably use another mechanism for versioning docs. As for color alignment etc., I will let the OV doc team open PRs to that accord.

**Review by alexsu52 — APPROVED** [review]
It looks better. Thanks.

**Comment by AlexKoff88** [comment]
I am ok with the changes. But the resource alone is hard to percept alone: https://vshampor.github.io/nncf/. However, it can be used already for a reference from other parts of NNCF documentation, e.g. OpenVINO product docs or NNCF developer docs (READMEs).

**Review by AlexKoff88 — APPROVED** [review]

**Comment by vshampor** [comment]
The TF precommit failure is caused by CI issues.

**Comment by vshampor** [comment]
The TF precommit failure is caused by CI issues.

**Pull request merged**
