### PR TITLE
Set abs criterion for magnitude pruning by default

### PR DESCRIPTION
**Pull request by vanyalzr**

### CODE REVIEW

**Comment by alexsu52** [comment]
@vanyalzr Will users achieve the claimed results using provided config files after this change?

**Comment by vanyalzr** [comment]
> @vanyalzr Will users achieve the claimed results using provided config files after this change?

Abs importance criterion gives better performing models in most cases in my experiments than normed abs, will update results accordingly.

**Comment by vshampor** [comment]
@vanyalzr is this still relevant?

**Comment by vanyalzr** [comment]
closing for now

**Pull request closed without merging**
