### PR TITLE
Upgrade ultralytics to 8.0.170

### PR DESCRIPTION
**Pull request by nikita-savelyevv**
### Changes

Upgrade ultralytics to 8.0.170

### Reason for changes

For some reason yolo samples started to fail. Upgrading ultralytics solves this issue because the later version contains these changes: https://github.com/ultralytics/ultralytics/commit/a7419617a6f2f74849161f3faa5b65d2cef92bd5

### Related tickets

120311

### Tests

Build 82 passed

### CODE REVIEW

**Comment by nikita-savelyevv** [comment]
run pylint pre-commit tests
run openvino pre-commit tests

**Comment by nikita-savelyevv** [comment]
run pylint pre-commit tests
run pytorch pre-commit tests
run tensorflow pre-commit tests
run openvino pre-commit tests
run onnx pre-commit tests

**Review by alexsu52 — COMMENTED** [review]
Why did you upgrade ultralytics to 8.0.170 instead off the latest version?

**Comment by nikita-savelyevv** [comment]
run pylint pre-commit tests
run pytorch pre-commit tests
run tensorflow pre-commit tests
run openvino pre-commit tests
run onnx pre-commit tests

**Review by alexsu52 — APPROVED** [review]

**Pull request merged**
