### PR TITLE
Fix for num_workers=0 for init_dataloader

### PR DESCRIPTION
**Pull request by mkaglins**
Fix for LeGR slowdown in multiprocessing-distributed mode due to` num_workers=0` for init loader (that was set to fix tests fails due to bug in Pytorch). 
Currently, num workers for init loader in examples will be set as needed for distributed mode. And only in tests `num_workers=0` will be used by redefining functions with data loaders creation.

### CODE REVIEW

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by mkaglins** [comment]
Jenkins please retry a build

**Review by AlexanderDokuchaev — APPROVED** [review]
I think that it's should be described in changelog @vshampor.

**Review by alexsu52 — COMMENTED** [review]
What do you think about providing this as a parameter instead of the env variable? Will you document this WA?

**Comment by mkaglins** [comment]
> What do you think about providing this as a parameter instead of the env variable? Will you document this WA?

1) Env variable was chosen as change with minimal impact to interface and code (+ potential reverting of this changes when it will not be needed anymore). 
It was discussed and chosen with @vshampor offline. Also, you can find his opinion in the comment above. 

2) As for the documentation for this WA as @vshampor mentioned above it is just an internal change. I can add comments about it to code where this env variable is used.

**Comment by alexsu52** [comment]
> 
> 
> > What do you think about providing this as a parameter instead of the env variable? Will you document this WA?
> 
>     1. Env variable was chosen as change with minimal impact to interface and code (+ potential reverting of this changes when it will not be needed anymore).
>        It was discussed and chosen with @vshampor offline. Also, you can find his opinion in the comment above.
> 
>     2. As for the documentation for this WA as @vshampor mentioned above it is just an internal change. I can add comments about it to code where this env variable is used.

It looks like that it needs only for testing. Thus, I would suggest writing a test without adding any functionality to the examples which need only for testing. For example, you can decorate `create_data_loaders` to set `num_workers`.

**Comment by mkaglins** [comment]
> > > What do you think about providing this as a parameter instead of the env variable? Will you document this WA?
> > 
> > 
> > ```
> > 1. Env variable was chosen as change with minimal impact to interface and code (+ potential reverting of this changes when it will not be needed anymore).
> >    It was discussed and chosen with @vshampor offline. Also, you can find his opinion in the comment above.
> > 
> > 2. As for the documentation for this WA as @vshampor mentioned above it is just an internal change. I can add comments about it to code where this env variable is used.
> > ```
> 
> It looks like that it needs only for testing. Thus, I would suggest writing a test without adding any functionality to the examples which need only for testing. For example, you can decorate `create_data_loaders` to set `num_workers`.

Sounds reasonable, I will implement such fix.

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by mkaglins** [comment]
@alexsu52 Please, check discussed changes.

**Review by alexsu52 — APPROVED** [review]

**Comment by mkaglins** [comment]
@alexsu52 Successful run of `test_sota_checkpoints`: https://adas-ci-icv.inn.intel.com/job/NNCF/job/nightly/job/ubuntu20_eval/514/

**Pull request merged**
