### PR TITLE
Rename prepare_for_inference to strip

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
### Changes

rename `prepare_for_inference` to `strip`

### Related tickets

107779

### CODE REVIEW

**Comment by AlexanderDokuchaev** [comment]
https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/accuracy_control/backend.py#L138
Is's same prepare_for_inference? Need to rename?

**Review by alexsu52 — APPROVED** [review]
LGTM

**Comment by alexsu52** [comment]
> https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/accuracy_control/backend.py#L138 Is it same `prepare_for_inference`? Need to rename?

@andrey-churkin could you comment?

**Review by vshampor — APPROVED** [review]

**Comment by andrey-churkin** [comment]
> > https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/accuracy_control/backend.py#L138 Is it same `prepare_for_inference`? Need to rename?
> 
> @andrey-churkin could you comment?

This method needed to compile model.

**Pull request merged**
