### PR TITLE
Update torch to 2.0.1 for ptq tests

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
### Changes

- Update torch to 2.0.1 
- Disable used fused attention operation `aten::scaled_dot_product_attention` 

### Related tickets

112589

- [x] build: 62,63

### CODE REVIEW

**Comment by AlexanderDokuchaev** [comment]
run pytorch pre-commit tests

**Comment by AlexanderDokuchaev** [comment]
run pytorch pre-commit tests

**Review by alexsu52 — APPROVED** [review]
Thanks!

**Comment by AlexanderDokuchaev** [comment]
No any degradation by this changes, but some models have changed metrics (more details in ticket 112589)

**Pull request merged**
