### PR TITLE
Linear output shape collection fix

### PR DESCRIPTION
**Pull request by daniil-lyakhov**
### Changes

Output shape calculation for linear layers in case of the output edge is absent was added.

`DisconectedGraphModel` in tests was fixed to be actually disconnected

### Reason for changes

Pruning isn't working in DOR due to latest linear layer has no output edge because of output node absence

### Tests

Tests was updated

### CODE REVIEW

**Comment by nikita-savelyevv** [comment]
Verified on OTE's DOR. The issue does not appear anymore.

**Review by nikita-savelyevv — APPROVED** [review]
Verified on OTE's DOR. The issue does not appear anymore.

**Comment by aiarkinx** [comment]
run openvino pre-commit tests

**Comment by aiarkinx** [comment]
run onnx pre-commit tests

**Comment by aiarkinx** [comment]
run build

**Review by vshampor — APPROVED** [review]

**Review by alexsu52 — APPROVED** [review]

**Review by ljaljushkin — APPROVED** [review]

**Review by AlexanderDokuchaev — APPROVED** [review]

**Pull request merged**
