### PR TITLE
Add quantize_with_accuracy_control example for ONNX

### PR DESCRIPTION
**Pull request by andrey-churkin**
### Changes

- Add quantize_with_accuracy_control example for ONNX

TODO:
- [x] Add README.md

### CODE REVIEW

**Comment by andrey-churkin** [comment]
@kshpv @alexsu52 Please review

**Review by kshpv — APPROVED** [review]

**Review by alexsu52 — CHANGES_REQUESTED** [review]
Please add a test for the example.

**Comment by andrey-churkin** [comment]
successful build # 253

**Review by alexsu52 — APPROVED** [review]
LGTM

**Pull request merged**
