### PR TITLE
Fix model_creation bug in TF

### PR DESCRIPTION
**Pull request by kshpv**

### CODE REVIEW

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Started 423 build

**Comment by pfinashx** [comment]
Jenkins please retry a build

**Review by alexsu52 — APPROVED** [review]

**Comment by pfinashx** [comment]
Started full E2E build 282

**Comment by kshpv** [comment]
Jenkins please retry a build

**Comment by kshpv** [comment]
@vshampor or @alexsu52 please, merge if satisfied

**Pull request merged**
