### PR TITLE
Launch BN adaptation for quantization only for non-zero sample values

### PR DESCRIPTION
**Pull request by vshampor**
### Changes

NNCFConfig will no longer require to have a BN adaptation data loader registered if the number of BN adaptation samples is set to 0 in the quantization algorithm (and if the only required compression is quantization).

### Reason for changes

This makes for easier debug/reproducer runs of quantization algo in a scratch file or a temporary Python console.

### Related tickets

N/A

### Tests

tests.torch.quantization.test_algo_quantization.test_quantization_can_be_run_with_no_data_loaders_if_zero_init_samples

### CODE REVIEW

**Review by ljaljushkin — APPROVED** [review]

**Review by alexsu52 — CHANGES_REQUESTED** [review]
Could you elaborate on what would change for the user? I mean what behavior was and will come for the following scenarios:
- BN adaptation parameters in the config and number of BN adaptation samples > 0.
- BN adaptation parameters in the config and number of BN adaptation samples == 0.
- There are no BN adaptation parameters in the config.

**Comment by vshampor** [comment]
> Could you elaborate on what would change for the user? I mean what behavior was and will come for the following scenarios:
> 
> * BN adaptation parameters in the config and number of BN adaptation samples > 0.
> * BN adaptation parameters in the config and number of BN adaptation samples == 0.
> * There are no BN adaptation parameters in the config.

Before: 
* BN adaptation parameters in the config and number of BN adaptation samples > 0 - fails if the BN adaptation data loader is not provided.
* BN adaptation parameters in the config and number of BN adaptation samples == 0 - fails if the BN adaptation data loader is not provided.
* There are no BN adaptation parameters in the config - fails if the BN adaptation data loader is not provided since a default non-zero value BN adaptation samples is used in this case.

After:
* BN adaptation parameters in the config and number of BN adaptation samples > 0 - same as in the "Before" section.
* BN adaptation parameters in the config and number of BN adaptation samples == 0 - does not fail if the BN adapation data loader is not provided, calls to BN adaptation do nothing.
* There are no BN adaptation parameters in the config - same as in the "Before" section.

**Comment by alexsu52** [comment]
> > Could you elaborate on what would change for the user? I mean what behavior was and will come for the following scenarios:
> > 
> > * BN adaptation parameters in the config and number of BN adaptation samples > 0.
> > * BN adaptation parameters in the config and number of BN adaptation samples == 0.
> > * There are no BN adaptation parameters in the config.
> 
> Before:
> 
>     * BN adaptation parameters in the config and number of BN adaptation samples > 0 - fails if the BN adaptation data loader is not provided.
> 
>     * BN adaptation parameters in the config and number of BN adaptation samples == 0 - fails if the BN adaptation data loader is not provided.
> 
>     * There are no BN adaptation parameters in the config - fails if the BN adaptation data loader is not provided since a default non-zero value BN adaptation samples is used in this case.
> 
> 
> After:
> 
>     * BN adaptation parameters in the config and number of BN adaptation samples > 0 - same as in the "Before" section.
> 
>     * BN adaptation parameters in the config and number of BN adaptation samples == 0 - does not fail if the BN adapation data loader is not provided, calls to BN adaptation do nothing.
> 
>     * There are no BN adaptation parameters in the config - same as in the "Before" section.
Currently, the BN adaptation algorithm is a mandatory initialization step of the quantization pipeline. It looks like you changed this behavior in the third case. I'm not sure that the stated reason is enough to approve changes.

**Comment by vshampor** [comment]
The BN adaptation algorithm application is default, not mandatory. The override mechanism here - setting a config parameter to 0 - is explicit and cannot be set by the user by mistake, only deliberately. If the user gives no mention of the BN adaptation algo, the behaviour with this PR is the same as before the PR - the algo will fail if no BN adaptation data loader is specified, and if it is specified, will run a default number of BN adaptation samples (1000, if I recall correctly).

**Pull request merged**
