### PR TITLE
Add logs for user guiding better

### PR DESCRIPTION
**Pull request by UsingtcNower**

### CODE REVIEW

**Comment by daniil-lyakhov** [comment]
Greetings @UsingtcNower! Thank you for your interest in the NNCF Filter Pruning algorithm!

I've checked your changes, and it looks like this warning is ambiguous: this information is present in the [pruning statistics](https://github.com/openvinotoolkit/nncf/blob/develop/docs/compression_algorithms/Pruning.md#filter-pruning-statistics). Please check the filter pruning statistics for identity pruning masks and confirm it shows that pruning masks are identity.

In case you are using pruning algorithm in your custom pipeline, you can print statistics using following code:
```
compression_ctrl, compressed_model = create_compressed_model(...)
statistics = compression_ctrl.statistics()
logger.info(statistics.to_str())
```

**Comment by UsingtcNower** [comment]
> Greetings @UsingtcNower! Thank you for your interest in the NNCF Filter Pruning algorithm!
> 
> I've checked your changes, and it looks like this warning is ambiguous: this information is present in the [pruning statistics](https://github.com/openvinotoolkit/nncf/blob/develop/docs/compression_algorithms/Pruning.md#filter-pruning-statistics). Please check the filter pruning statistics for identity pruning masks and confirm it shows that pruning masks are identity.
> 
Thanks for your reply @daniil-lyakhov ! 
Let me illustrate what I'm going through, the printed filter pruning statistics show that Pruning Level is zero, but I can't tell why. The filter pruning statistics looks like a summary, and the warning here looks like a check. Hopefully it can help users like me.
> In case you are using pruning algorithm in your custom pipeline, you can print statistics using following code:
> 
> ```
> compression_ctrl, compressed_model = create_compressed_model(...)
> statistics = compression_ctrl.statistics()
> print(statistics.to_str())
> ```

**Comment by daniil-lyakhov** [comment]
@UsingtcNower, could you please attach NNCF logs with this warning turned on?

**Comment by UsingtcNower** [comment]
> @UsingtcNower, could you please attach NNCF logs with this warning turned on?

Here I attach the NNCF logs.
[nncf_logs.log](https://github.com/openvinotoolkit/nncf/files/14435275/nncf_logs.log)

**Review by daniil-lyakhov — APPROVED** [review]

**Comment by alexsu52** [comment]
@UsingtcNower Thanks for the contribution!

**Pull request merged**
