### PR TITLE
Move test_templates to cross_fw directory

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
### Changes

Move all templates classes to separate directory.

### Reason

Improve organization of test files and maintainability

### CODE REVIEW

**Comment by KodiaqQ** [comment]
@AlexanderDokuchaev, why is the current placement wrong? What would we get from the move?
Any obvious reasons aside from the "improvements"?

**Comment by AlexanderDokuchaev** [comment]
@KodiaqQ  https://github.com/openvinotoolkit/nncf/blob/develop/docs/styleguide/PyGuide.md#63-folder-structure

**Comment by AlexanderDokuchaev** [comment]
> > @KodiaqQ https://github.com/openvinotoolkit/nncf/blob/develop/docs/styleguide/PyGuide.md#63-folder-structure
> 
> Since you've started following the style guides, please review all tests in the NNCF, not only `test_templates`.

@KodiaqQ  If you think that something is not following the style guides, you are free to create PR by yourself.

**Comment by AlexanderDokuchaev** [comment]
@KodiaqQ This PR just moves test_templates directory to cross_fw to align with the code style, It is a completed job.
Do you have any change requests for this PR?

**Comment by KodiaqQ** [comment]
> @KodiaqQ This PR just moves test_templates directory to cross_fw to align with the code style, It is a completed job. Do you have any change requests for this PR?

No.

**Pull request merged**
