### PR TITLE
Add an option to optimize logarithms of quantizer scales instead of scales directly

### PR DESCRIPTION
**Pull request by vshampor**

### CODE REVIEW

**Review by krodyush — APPROVED** [review]
looks like it does the same what I requested in  https://github.com/openvinotoolkit/nncf/pull/278

**Comment by vshampor** [comment]
@krodyush could you verify with your use cases that this indeed improves convergence?

**Comment by krodyush** [comment]
Yes I could. But it require time for preparing and run experiments.

**Comment by vshampor** [comment]
> Yes I could. But it require time for preparing and run experiments.

Please start the experiments.

**Comment by krodyush** [comment]
checked. it still works. 1 epoch tune for packed bert-qa model.
exact_match metric for "logarithm_scale": true better by ~1%

**Comment by vshampor** [comment]
@krodyush , thanks.

**Pull request merged**
