### PR TITLE
Conformance test with Process

### PR DESCRIPTION
**Pull request by KodiaqQ**
### Changes

- Updated conformance test with Process while validation to avoid main process failure

### Reason for changes

- More robust conformance test

### CODE REVIEW

**Comment by KodiaqQ** [comment]
Conformance test run - №25

**Comment by KodiaqQ** [comment]
run pytorch pre-commit tests

**Comment by KodiaqQ** [comment]
run tensorflow pre-commit tests

**Review by alexsu52 — COMMENTED** [review]
Could you run ptq_timm test for each model in a separate process to improve the robustness of the conformance tests?

**Comment by daniil-lyakhov** [comment]
Full traceback in case of an error would be great IMHO

**Review by alexsu52 — COMMENTED** [review]
LGTM, Could you provide a green build?

**Comment by KodiaqQ** [comment]
> LGTM, Could you provide a green build?

Green build - №36

**Review by alexsu52 — APPROVED** [review]

**Pull request merged**
