### PR TITLE
Remove upper bound from `scipy` version

### PR DESCRIPTION
**Pull request by p-wysocki**
### Changes

Removal of upper bounds from `scipy` version.

### Reason for changes

 - `scipy<1.11.1` has security vulnerability (see ticket)
 -  The upper bound is causing pip conflicts in https://github.com/openvinotoolkit/openvino/pull/19458

### Related tickets

117438

### CODE REVIEW

**Comment by p-wysocki** [comment]
@KodiaqQ @andrey-churkin could you please take a look?

**Comment by p-wysocki** [comment]
The failing CI check seems to be broken: 
```bash
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_9656188f-297d-4090-a9a7-0efbf2961cf3/f302203e-2cc9-42be-baaf-32b960b83cdd.tar.gz. return code: 2.
```

**Comment by MaximProshin** [comment]
@vshampor , could you please investigate why API check is failed?

**Comment by vshampor** [comment]
The failure seems to be due to this:
https://github.com/actions/checkout/issues/1448
i.e. an upstream bug.

**Review by vshampor — APPROVED** [review]

**Comment by alexsu52** [comment]
run pytorch pre-commit tests

**Review by alexsu52 — COMMENTED** [review]
I would recommend to get install tests results before merging this PR.

**Comment by p-wysocki** [comment]
@alexsu52 I reran the Pylint, the new run (pylint #4409) passed. Is there anything else we need for merge?

**Comment by vshampor** [comment]
Install tests running:
TF: 368
PT GPU: 256
OV: 259
ONNX: 228

Win:
TF: 149
PT CPU: 153
OV: 149
ONNX: 151

**Comment by alexsu52** [comment]
run pylint pre-commit tests

**Review by alexsu52 — APPROVED** [review]
Thanks for the contribution.

**Pull request merged**
