### PR TITLE
[TF] Add pruned retinanet and resnet50 to sota test

### PR DESCRIPTION
**Pull request by evgeniya-egupova**

### CODE REVIEW

**Comment by evgeniya-egupova** [comment]
test build #720

**Comment by evgeniya-egupova** [comment]
Jenkins please retry a build

**Comment by alexsu52** [comment]
Could you provide CI validation results?

**Comment by evgeniya-egupova** [comment]
> @evgeniya-egupova Could you provide CI validation results?

There is currently a proxy issue in CI, so I will provide results later, when it will be fixed

**Review by daniil-lyakhov — APPROVED** [review]

**Comment by evgeniya-egupova** [comment]
Jenkins please retry a build

**Comment by evgeniya-egupova** [comment]
Jenkins please retry a build

**Pull request merged**
