### PR TITLE
Add Mask-RCNN-R50FPN-INT8 config for mmdetection

### PR DESCRIPTION
**Pull request by vanyalzr**

### CODE REVIEW

**Comment by vshampor** [comment]
@vanyalzr please extend the `tests\test_sanity_third_party.py` with a corresponding case and add the results into both the frontpage README.md table and into `third_party_integration\mmdetection\README.md`

**Comment by vanyalzr** [comment]
Jenkins please retry a build

**Comment by vanyalzr** [comment]
@vshampor done

**Comment by vshampor** [comment]
Mock datasets to be extended for the mask input cases and consistency with bboxes.

**Pull request merged**
