### PR TITLE
[OpenVINO] Add Slice metatype

### PR DESCRIPTION
**Pull request by kshpv**
### Changes

Adds Slice operation - https://docs.openvino.ai/2022.3/openvino_docs_ops_movement_Slice_8.html
As a result the performance for modnet_webcam_portrait_matting from DLB was improved (local measurement)
from 44 FPS till 72 FPS.
image

### Reason for changes

Fix incorrect quantization scheme due to unknown metatype

### Related tickets

144218

### Tests

Manually

### CODE REVIEW

**Review by alexsu52 — APPROVED** [review]
LGTM

**Comment by kshpv** [comment]
ptq build - 437

**Comment by KodiaqQ** [comment]
Don't we need to align `nncf/common/hardware/configs/cpu.json` and other schemes also?

**Comment by kshpv** [comment]
> ptq build - 437

build is passed

**Comment by kshpv** [comment]
> Don't we need to align `nncf/common/hardware/configs/cpu.json` and other schemes also?

I am not sure how to make this alignment. Could you clarify?

**Comment by KodiaqQ** [comment]
> I am not sure how to make this alignment. Could you clarify?

Our schemes from the `nncf/common/hardware/configs` are the basement for the quantization. Other NNCF parts (like metatypes) should be aligned with them, not vice-versa. For now, I don't see the `Slice` operation in `nncf/common/hardware/configs/cpu.json`.

**Comment by KodiaqQ** [comment]
> build is passed

Are there any models in our conformance run that contain Slice operation?

**Comment by kshpv** [comment]
> > build is passed
> 
> Are there any models in our conformance run that contain Slice operation?



> > I am not sure how to make this alignment. Could you clarify?
> 
> Our schemes from the `nncf/common/hardware/configs` are the basement for the quantization. Other NNCF parts (like metatypes) should be aligned with them, not vice-versa. For now, I don't see the `Slice` operation in `nncf/common/hardware/configs/cpu.json`.

HWConfigOpName was added for Slice op and added to hw configs as well.

**Comment by kshpv** [comment]
> > build is passed
> 
> Are there any models in our conformance run that contain Slice operation?

I did not check that, but all models passed

**Comment by KodiaqQ** [comment]
> I did not check that, but all models passed

Why did you run this test then? What should it show?

**Comment by kshpv** [comment]
> > I did not check that, but all models passed
> 
> Why did you run this test then? What should it show?

To be sure that there is no regression on PTQ scope it was asked by other reviewer

**Review by KodiaqQ — APPROVED** [review]

**Pull request merged**
