### PR TITLE
Common logger

### PR DESCRIPTION
**Pull request by alexsu52**
Using common Logger implementation for the NNCF with PyTorch and TensorFlow backends.

### CODE REVIEW

**Comment by alexsu52** [comment]
Jenkins please retry a build

**Comment by gadylshintr** [comment]
Logs duplication occurs:
image

**Comment by vshampor** [comment]
Jenkins please retry a build

**Review by gadylshintr — APPROVED** [review]
No logs duplication.

**Comment by alexsu52** [comment]
Jenkins please retry a build

**Review by vshampor — APPROVED** [review]

**Pull request merged**
