### PR TITLE
Renamed pruning_rate to pruning_level for TF pruning controller

### PR DESCRIPTION
**Pull request by nikita-savelyevv**
Renamed `pruning_rate` to `pruning_level` for TF pruning controller

### Reason for changes

Everywhere in the codebase `pruning_level` is used for compression rate of pruning controller except multiple places in TF implementation of pruning controller

### CODE REVIEW

**Review by alexsu52 — COMMENTED** [review]
Could you take a look at other places in the code where `pruning_rate` is used: For example: https://github.com/openvinotoolkit/nncf/blob/cc3b34aab39061791afae5c2552fcd339b139c4e/nncf/torch/pruning/filter_pruning/algo.py#L606

**Comment by nikita-savelyevv** [comment]
> Could you take a look at other places in the code where `pruning_rate` is used: For example:
> 
> https://github.com/openvinotoolkit/nncf/blob/cc3b34aab39061791afae5c2552fcd339b139c4e/nncf/torch/pruning/filter_pruning/algo.py#L606

Do you mean we should replace it with `pruning_level` in all other places?

**Comment by alexsu52** [comment]
> > Could you take a look at other places in the code where `pruning_rate` is used: For example:
> > https://github.com/openvinotoolkit/nncf/blob/cc3b34aab39061791afae5c2552fcd339b139c4e/nncf/torch/pruning/filter_pruning/algo.py#L606
> 
> Do you mean we should replace it with `pruning_level` in all other places?

What I mean is to take a look at another part of the code and check that it is legal to use `pruning_rate` in another part of the code.

**Comment by nikita-savelyevv** [comment]
> What I mean is to take a look at another part of the code and check that it is legal to use `pruning_rate` in another part of the code.

In my opinion it would be better to rename `pruning_rate` to `pruning_level` everywhere for consistency sake, because in the most cases it is referred to as `pruning_level` at the moment. 

At the same time however, I think `pruning_rate` is a better name for it because it fits well together with `compression_rate`: `compression_rate` is a general compression backend -agnostic name and `pruning_rate` is how `compression_rate` is referred to when pruning backend is used. But I don't know the reasons why it was decided to make it `pruning_level` despite this so I am not confident enough to rename it all back to `pruning_rate`.

**Comment by alexsu52** [comment]
> > What I mean is to take a look at another part of the code and check that it is legal to use `pruning_rate` in another part of the code.
> 
> In my opinion it would be better to rename `pruning_rate` to `pruning_level` everywhere for consistency sake, because in the most cases it is referred to as `pruning_level` at the moment.
> 
> At the same time however, I think `pruning_rate` is a better name for it because it fits well together with `compression_rate`: `compression_rate` is a general compression backend -agnostic name and `pruning_rate` is how `compression_rate` is referred to when pruning backend is used. But I don't know the reasons why it was decided to make it `pruning_level` despite this so I am not confident enough to rename it all back to `pruning_rate`.

Thank you for your comment! First, the naming must be consistent. Let's do it and then we'll discuss renaming.

**Review by alexsu52 — APPROVED** [review]
LGTM

**Review by ljaljushkin — APPROVED** [review]

**Review by daniil-lyakhov — APPROVED** [review]

**Pull request merged**
