### PR TITLE
 [PTQ] Extend num_samples=1 for weights statistics collection for all backends

### PR DESCRIPTION
**Pull request by kshpv**
### Changes

Make num_samples=1 for weights statistics collection for all backends

### Reason for changes

Speed up statistics collection for ONNX, Torch.
Generalize logic.

### Related tickets

N/A

### Tests

Update `test_get_stat_collector`

### CODE REVIEW

**Comment by kshpv** [comment]
run pytorch pre-commit tests

**Review by alexsu52 — COMMENTED** [review]
Could you provide speed-up numbers for this PR?

**Comment by kshpv** [comment]
I made local measurements of quantization for the three models from `test_ptq_regression`: 
Speedup:
Mobilenetv2 ~15%
Resnet50 ~ 17%
Efficiennet-lite4 ~ 42.5%

**Comment by kshpv** [comment]
Locally I got the following results from conformance test for ONNX and Torch:

develop branch

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/akashapo/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/akashapo/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">




Model | Backend | Metric name | Metric value | Metric diff | Num FQ | RAM MiB | Quant. time | Total time
-- | -- | -- | -- | -- | -- | -- | -- | --
timm/levit_128 | ONNX |   |   |   | 177 | 958 | 0:00:49 | 0:00:55
timm/levit_128 | TORCH |   |   |   | 179 | 733 | 0:00:37 | 0:00:47
timm/mobilenetv3_small_050 | ONNX |   |   |   | 80 | 834 | 0:00:09 | 0:00:12
timm/mobilenetv3_small_050 | TORCH |   |   |   | 80 | 801 | 0:00:21 | 0:00:25
timm/resnet18 | ONNX |   |   |   | 30 | 1197 | 0:00:17 | 0:00:23
timm/resnet18 | TORCH |   |   |   | 30 | 870 | 0:00:12 | 0:00:18



</body>

This PR

</html>


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/akashapo/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/akashapo/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



Model | Backend | Metric name | Metric value | Metric diff | Num FQ | RAM MiB | Quant. time | Total time
-- | -- | -- | -- | -- | -- | -- | -- | --
timm/levit_128 | ONNX |   |   |   | 177 | 961 | 0:00:42 | 0:00:49
timm/levit_128 | TORCH |   |   |   | 179 | 731 | 0:00:34 | 0:00:45
timm/mobilenetv3_small_050 | ONNX |   |   |   | 80 | 772 | 0:00:08 | 0:00:11
timm/mobilenetv3_small_050 | TORCH |   |   |   | 80 | 800 | 0:00:20 | 0:00:24
timm/resnet18 | ONNX |   |   |   | 30 | 1196 | 0:00:12 | 0:00:18
timm/resnet18 | TORCH |   |   |   | 30 | 853 | 0:00:11 | 0:00:17



</body>

</html>


Boost for ONNX ~ 16%
Boost for Torch ~ 4-5%

**Review by KodiaqQ — APPROVED** [review]

**Review by alexsu52 — APPROVED** [review]
LGTM

**Review by AlexanderDokuchaev — APPROVED** [review]

**Pull request merged**
