### PR TITLE
Fix segmentation fault

### PR DESCRIPTION
**Pull request by andrey-churkin**
### Changes

Set num_workers = 0

### Reason for changes

Segmentation fault

### Related tickets

Ref: 151081

### CODE REVIEW

**Comment by andrey-churkin** [comment]
NNCF/nightly/test_examples_3.10: # 91

**Comment by alexsu52** [comment]
Check these changes in Windows as well

**Review by alexsu52 — COMMENTED** [review]
Check these changes in Windows as well

**Comment by andrey-churkin** [comment]
NNCF/nightly/windows/test-examples_3.10 : # 90

**Comment by andrey-churkin** [comment]
All tests have been passed.

**Review by alexsu52 — APPROVED** [review]

**Pull request merged**
