### PR TITLE
Fix last win tests (#1769)

### PR DESCRIPTION
**Pull request by vshampor**

### CODE REVIEW

**Comment by ksilligan** [comment]
run pylint pre-commit tests

**Comment by ksilligan** [comment]
run pylint pre-commit tests

**Comment by ksilligan** [comment]
run tensorflow pre-commit tests

**Comment by ksilligan** [comment]
run openvino pre-commit tests

**Comment by ksilligan** [comment]
run onnx pre-commit tests

**Comment by ksilligan** [comment]
run openvino pre-commit tests

**Review by MaximProshin — APPROVED** [review]

**Comment by MaximProshin** [comment]
approved for merging to the release

**Pull request merged**
