### PR TITLE
Fk/update packages versions

### PR DESCRIPTION
**Pull request by FyodorK**
Add definitive versions of the packages to setup.py only.

### CODE REVIEW

**Review by vshampor — APPROVED** [review]

**Comment by ljaljushkin** [comment]
@vshampor, @FyodorK 

With the latest develop branch after installation of required dependencies by `python setup.py install` I have a broken environment.
Any pip command fails with an error:
```
AttributeError: '_NamespacePath' object has no attribute 'sort'
```
my Python version is 3.6.9

Looks like this is a bug with pip. People recommend([1](https://github.com/googleapis/google-cloud-python/issues/2990), [2](https://github.com/pypa/pip/issues/4216)) upgrading to the latest pip with setuptools >= 34.3.0
Probably, we should check this in a setup.py to prevent errors like this.

**Comment by ljaljushkin** [comment]
I've created a new virtual environment, upgraded pip and `python setup.py install` fails with error:
```
  File "/tmp/easy_install-s0gu5pna/pandas-1.2.0rc0/setup.py", line 20, in <module>
    import os
ModuleNotFoundError: No module named 'numpy'
```
Do we support Python3.8 only? What Python version is used in CI?

**Comment by FyodorK** [comment]
According to requirements it is "Ubuntu* 18.04 or later (64-bit)"

**Comment by vshampor** [comment]
@ljaljushkin looks like there are indeed problems with the current setup.py, as indicated by multiple nightly test failures. @FyodorK will investigate and provide a fix.

**Pull request merged**
