### PR TITLE
[PTQ][OV] Add GroupNormalization type

### PR DESCRIPTION
**Pull request by KodiaqQ**
### Changes

- Added new operation - GroupNormalization

### Reason for changes

- Performance degradations that are caused by not correct quantization scheme
- New operation support

### Related tickets

- 119821
- 119335

### Tests

- TBD

### CODE REVIEW

**Comment by KodiaqQ** [comment]
run pylint pre-commit tests
run pytorch pre-commit tests
run tensorflow pre-commit tests
run onnx pre-commit tests

**Comment by KodiaqQ** [comment]
run pylint pre-commit tests
run pytorch pre-commit tests
run tensorflow pre-commit tests
run openvino pre-commit tests
run onnx pre-commit tests

**Comment by KodiaqQ** [comment]
run pylint pre-commit tests
run pytorch pre-commit tests
run openvino pre-commit tests
run onnx pre-commit tests

**Review by alexsu52 — APPROVED** [review]
LGTM

**Comment by KodiaqQ** [comment]
This PR is blocked with the OpenVINO release since we need to have `opset12` due to the error: `No name 'opset12' in module 'openvino.runtime'`.
cc @alexsu52

**Comment by KodiaqQ** [comment]
run pylint pre-commit tests

**Comment by KodiaqQ** [comment]
run pylint pre-commit tests

**Pull request merged**
