### PR TITLE
Fix tabulate for windows

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
### Changes

Use grids without unsupported symbols for windows

### Related tickets

136331

### CODE REVIEW

**Comment by AlexanderDokuchaev** [comment]
view/all/job/ci-maintenance/job/rmkh-dev/job/NNCF/job/nightly/job/windows/job/test-examples/14/

For windows will be forced default format like was in texttable
```
+------+------+
|   G1 |   H2 |
+======+======+
|    1 |    2 |
+------+------+
|    1 |    2 |
+------+------+
```

**Review by alexsu52 — COMMENTED** [review]
Please, provide test results for the Linux test_examples build as well.

**Comment by AlexanderDokuchaev** [comment]
nightly/job/test_examples/316

**Review by alexsu52 — APPROVED** [review]
LGTM

**Pull request merged**
