### PR TITLE
Support interpolate op in filter pruning

### PR DESCRIPTION
**Pull request by alexsu52**
Reopened [PR 982](https://github.com/openvinotoolkit/nncf/pull/982)

### CODE REVIEW

**Comment by vshampor** [comment]
I suppose this should be tested somehow. @daniil-lyakhov can you advise just how are the pruning ops per-framework covered by tests right now?

**Comment by daniil-lyakhov** [comment]
> I suppose this should be tested somehow. @daniil-lyakhov can you advise just how are the pruning ops per-framework covered by tests right now?

I think it's worth to make a test model with interpolation layers, which interpolate feature map (good interpolate) and a model with interpolation layer, which interpolate channel dimensions. Such cases should work fine due to symbolic mask propagation step

**Comment by alexsu52** [comment]
jenkins retest this please

**Review by vshampor — APPROVED** [review]

**Comment by vshampor** [comment]
Created ticket 93861 for adding pruning tests.

**Pull request merged**
