### PR TITLE
Add AutoQ end-to-end config for image classification samples (resnet50 and mobilenet_v2)

### PR DESCRIPTION
**Pull request by vuiseng9**

### CODE REVIEW

**Comment by vuiseng9** [comment]
@ljaljushkin

**Review by ljaljushkin — CHANGES_REQUESTED** [review]
Looks good to me. Please change the target branch from `develop` to `release_v160` to include them to the upcoming release.

**Comment by ljaljushkin** [comment]
Jenkins please retry a build

**Review by ljaljushkin — APPROVED** [review]
I'm ok with the changes. But not sure we need c675c10 from `develop` in the `release` branch.

**Pull request merged**
