### PR TITLE
Fix pylint

### PR DESCRIPTION
**Pull request by vinnamkim**
### Changes
Fix pylint for files where pylint check was missing in the meantime

### Reason for changes
Same as above

### Related tickets
89149

### CODE REVIEW

**Comment by vinnamkim** [comment]
retest this please

**Comment by vinnamkim** [comment]
retest this please

**Review by alexsu52 — APPROVED** [review]
Thanks for the contribution! Did you update the CI job? LGTM.

**Comment by vinnamkim** [comment]
> Thanks for the contribution! Did you update the CI job? LGTM.

CI was also updated to include the missing files.

**Pull request merged**
