### PR TITLE
Move rb sparsity algo to TFTransformationLayout

### PR DESCRIPTION
**Pull request by daniil-lyakhov**
- [x] Have checked separable convolutions processed correctly

### CODE REVIEW

**Comment by daniil-lyakhov** [comment]
Jenkins please retry a build

**Comment by daniil-lyakhov** [comment]
Jenkins please retry a build

**Comment by daniil-lyakhov** [comment]
Jenkins please retry a build

**Review by alexsu52 — COMMENTED** [review]
Please, rebase your branch.

**Review by alexsu52 — APPROVED** [review]

**Pull request merged**
