### PR TITLE
Make OrderedEnum int based

### PR DESCRIPTION
**Pull request by nikita-savelyevv**
### Changes

Removed `OrderedEnum` and replaced its usages by `IntEnum`.

### Reason for changes

In general `OrderedEnum` should base on `IntEnum` because a method \_\_lt\_\_ is implemented for it where enum values are compared with "<" sign. This is not critical, but currently it complicates development of #1343. There, when an object of type `CompressionStage(OrderedEnum)` is being serialized by json, it throws an error, because it is ambiguous how to serialize a general enum object. Making `OrderedEnum` be based from `IntEnum` resolves this issue.

**Edit:** decided to remove `OrderedEnum` altogether and use `IntEnum` instead.

### CODE REVIEW

**Comment by vshampor** [comment]
We might still need ordered string enums. You can try to use multiple inheritance with `IntEnum`/`StrEnum` and an `OrderedEnumBase` (defining comparison magic methods), and then have `class OrderedEnum(IntEnum, OrderedEnumBase)` and `class OrderedStrEnum(StrEnum, OrderedEnumBase)`.

**Comment by nikita-savelyevv** [comment]
> 
There is no usage for OrderedStrEnum as of now. Maybe its better to create it when it will be required? 

Also, I don't think one would ever need an ordered string enum.

**Comment by nikita-savelyevv** [comment]
> Whoever introduced the original ordered enum needed it. For reasons of compatibility should use `OrderedStrEnum` instead of an `OrderedEnum` wherever string enums were inherited from the original `OrderedEnum`.

According to the information I received. The only two use cases with string ordered enums were made by mistake. I fixed them by basing from regular enum.

**Review by alexsu52 — COMMENTED** [review]
It looks like you can replace `OrderedEnum` to `IntEnum` and remove `OrderedEnum` class from repository.

**Comment by nikita-savelyevv** [comment]
Replaced `OrderedEnum` with `IntEnum`

**Review by alexsu52 — APPROVED** [review]

**Review by vshampor — APPROVED** [review]

**Pull request merged**
