### PR TITLE
Added option --use_new_frontend to MO command line

### PR DESCRIPTION
**Pull request by pfinashx**
### Changes

Added option --use_new_frontend to MO command line in test_sota_chepoint.py

### Reason for changes

To test new OpenVino ONNX frontend

### CODE REVIEW

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Comment by pfinashx** [comment]
Jenkins please stop all builds

**Pull request closed without merging**
