### PR TITLE
Update StaticDatasetMock

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
### Changes

Add `get_static_dataset` function.

### CODE REVIEW

**Comment by AlexanderDokuchaev** [comment]
run tensorflow pre-commit tests

**Comment by AlexanderDokuchaev** [comment]
run tensorflow pre-commit tests

**Comment by vshampor** [comment]
@AlexanderDokuchaev RTFM:
https://github.com/openvinotoolkit/nncf/blob/develop/tests/common/README.md

**Comment by AlexanderDokuchaev** [comment]
run pytorch pre-commit tests

**Review by vshampor — APPROVED** [review]

**Pull request merged**
