### PR TITLE
Prohibit additional properties in scope_overrides section of NNCFConfig

### PR DESCRIPTION
**Pull request by vshampor**

### CODE REVIEW

**Review by alexsu52 — COMMENTED** [review]
Will I be able to run the config from the documentation https://github.com/openvinotoolkit/nncf/blob/2f231aa3903a286dafaa15eaae54758e2a2f346b/docs/compression_algorithms/Quantization.md after these changes?

**Comment by vshampor** [comment]
> Will I be able to run the config from the documentation https://github.com/openvinotoolkit/nncf/blob/2f231aa3903a286dafaa15eaae54758e2a2f346b/docs/compression_algorithms/Quantization.md after these changes?

Fixed

**Review by alexsu52 — COMMENTED** [review]
Please, add a test for the scope overrides of the quantization parameters.

**Comment by vshampor** [comment]
Tests TBA in 81528

**Pull request merged**
