### PR TITLE
Use explicit port IDs for parallel edge case instead of the parallel edge count

### PR DESCRIPTION
**Pull request by vshampor**
### Changes
Fixes the torch graph tracing to correctly handle parallel edge scenario in case when the tensors belonging to parallel edges do are interleaved in the order of the tensor arguments to a given traced torch op.

### Reason for changes
Bugfix

### Related tickets
113539

### Tests
precommit, E2E TBR

### CODE REVIEW

**Comment by vshampor** [comment]
run pytorch pre-commit tests

**Comment by vshampor** [comment]
run pytorch pre-commit tests

**Comment by vshampor** [comment]
test_examples build 7 is OK

**Comment by vshampor** [comment]
PT E2E run 368

**Review by alexsu52 — APPROVED** [review]
LGTM

**Pull request merged**
