### PR TITLE
[PTQ][PT] Added test to check export of FQ params

### PR DESCRIPTION
**Pull request by l-bat**
### Changes

Added a test for the Torch PTQ backend that verifies that common FQ params match to the FQ params in exported Torch model.

### Reason for changes

To improve code coverage

### Related tickets

100805

### Tests

test_quantizer_parameters_export

### CODE REVIEW

**Comment by l-bat** [comment]
run tensorflow pre-commit tests

**Comment by l-bat** [comment]
run pytorch pre-commit tests

**Review by alexsu52 — APPROVED** [review]

**Review by daniil-lyakhov — APPROVED** [review]
Appreciate your efforts, thanks a lot!

**Comment by l-bat** [comment]
run openvino pre-commit tests

**Pull request merged**
