### PR TITLE
Retry sanity sample runs on segfault

### PR DESCRIPTION
**Pull request by vshampor**
### Changes
As stated in the title

### Reason for changes
Working around sporadic segfaults in Torch sanity samples due to torch 2.0

### Related tickets
119128

### Tests
torch test_sanity_sample

### CODE REVIEW

**Comment by vshampor** [comment]
run onnx pre-commit tests
run openvino pre-commit tests
run tensorflow pre-commit tests

**Comment by AlexanderDokuchaev** [comment]
This workaround for sanity tests has already been rejected by @alexsu52 and myself in the discussion of https://github.com/openvinotoolkit/nncf/pull/2058

**Comment by vshampor** [comment]
> This workaround for sanity tests has already been rejected by @alexsu52 and myself in the discussion of #2058

Well, I don't reject it, I endorse it. I also see no relevant discussions either in #2092 or #2058

**Comment by vshampor** [comment]
> After #2149 it can be closed?

Indeed.

**Pull request closed without merging**
