### PR TITLE
[PTQ] Update BC for Split nodes

### PR DESCRIPTION
**Pull request by KodiaqQ**
### Changes

- Updated BC algorithm pipeline for specific Split cases.

### Reason for changes

- Accuracy degradation
- Wrong statistics calculation

### Related tickets

- 111542

### Tests

- Conformance run - post_training_quantization/124/

### CODE REVIEW

**Review by alexsu52 — COMMENTED** [review]
Does the conformance test include a model with split? I would recommend to add unit test for this changes as well.

**Comment by KodiaqQ** [comment]
> Does the conformance test include a model with split? I would recommend to add unit test for this changes as well.

It's not included. Do we really need such a huge model in the conformance?

**Comment by alexsu52** [comment]
> > Does the conformance test include a model with split? I would recommend to add unit test for this changes as well.
> 
> It's not included. Do we really need such a huge model in the conformance?

I think, the test will be enough.

**Review by alexsu52 — APPROVED** [review]
LGTM

**Comment by KodiaqQ** [comment]
Waiting for updates from @kshpv, for ONNX tests.

**Pull request merged**
