### PR TITLE
Extend NNCF logging by the device information where quantization was done

### PR DESCRIPTION
**Pull request by andrey-churkin**
### Changes

Extend NNCF logging by the device information where quantization was done

### Related tickets

Ref: 150780

### CODE REVIEW

**Comment by andrey-churkin** [comment]
post_training_quantization: Build # 470

**Comment by MaximProshin** [comment]
@andrey-churkin , will it work in all cases, e.g. when weights compression or QAT is used. 
+ @KodiaqQ , who had some additional suggestions.

**Comment by alexsu52** [comment]
@MaximProshin, are you going to add this information only in the test log not as part of the model?

**Comment by andrey-churkin** [comment]
@MaximProshin only for calibrate.py

**Review by KodiaqQ — APPROVED** [review]

**Comment by MaximProshin** [comment]
> @MaximProshin, are you going to add this information only in the test log not as part of the model?

I don't insist to have it in the model (not sure if it's even proper from the legacy perspective).

**Pull request merged**
