### PR TITLE
Add compression_lr_multiplier for tf part

### PR DESCRIPTION
**Pull request by a-ignatyev**
### Changes
As stated in the title

### Reason for changes
Alignment with the corresponding functionality in PT QAT

### Related tickets

54481

### Tests
tests/tensorflow/test_compression_lr_multiplier.py

### CODE REVIEW

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by FyodorK** [comment]
Jenkins please stop all builds

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by vshampor** [comment]
Will revisit this if the focus shifts to QAT in TF once more.

**Pull request closed without merging**
