### PR TITLE
Support for Python 3.6 was removed

### PR DESCRIPTION
**Pull request by andrey-churkin**
### Changes

The lowest supported python version was increased to 3.7.0

### Reason for changes

OpenVINO will deprecate support for the 3.6 version.

### Related tickets

N/A

### Tests

N/A

### CODE REVIEW

**Comment by andrey-churkin** [comment]
@vshampor @alexsu52 Are there any other places where I should make changes?

**Comment by alexsu52** [comment]
> @vshampor @alexsu52 Are there any other places where I should make changes?

maybe, requirements for tests and examples...

**Review by alexsu52 — COMMENTED** [review]
Please provide the results of the test_install build for TensorFlow and PyTorch backends.

**Review by vshampor — APPROVED** [review]
The install tests shouldn't be necessary since our CI runs on 3.8 everywhere anyway, and that behaviour is not defined by our setup.py and rather by the groovy pipelines/docker images.

**Comment by andrey-churkin** [comment]
@alexsu52 Please see job # 104 for TF backend

**Review by alexsu52 — APPROVED** [review]

**Pull request merged**
