### PR TITLE
Add AWQ to LLM hyperparams tuning example

### PR DESCRIPTION
**Pull request by l-bat**
### Changes

Add AWQ parameter to to LLM hyperparams tuning example
test_examples job: 228

### Tests

Updated `tests/cross_fw/examples/run_example.py::llm_tune_params`

### CODE REVIEW

**Comment by AlexKoff88** [comment]
@andreyanufr, @ljaljushkin please take a look as well.

**Comment by ljaljushkin** [comment]
What about considering data-aware without awq, first? 
Conformance test shows it gives a better similarity (group size and ratio are the same) and works faster. 
image

**Comment by ljaljushkin** [comment]
> Conformance test shows data-aware without awq gives a better similarity (group size and ratio are the same) and works faster. I wonder why do you have the opposite results. `group_size=64` `ratio=0.8` `mode=int4_sym` `tinyllama/tinyllama-1.1b-step-50k-105b` image

@l-bat 
do you have logs with similarity per configuration? Could you please post it there?

**Comment by l-bat** [comment]
TinyLLama shows better results with `awq=True` for `ratio=1.0`, so the AWQ algo is enabled for further experiments.

**Review by ljaljushkin — APPROVED** [review]

**Pull request merged**
