### PR TITLE
Fixed problem with shared weights in compression.

### PR DESCRIPTION
**Pull request by andreyanufr**
### Changes

Fixed problem with shared weights in compression.

### Reason for changes

Problem with some LLMs with shared weights.

### CODE REVIEW

**Comment by andreyanufr** [comment]
run pytorch pre-commit tests

**Comment by andreyanufr** [comment]
run pytorch pre-commit tests

**Comment by andreyanufr** [comment]
run pytorch pre-commit tests

**Comment by andreyanufr** [comment]
run tensorflow pre-commit tests

**Review by alexsu52 — COMMENTED** [review]
Please, add a test.

**Comment by andreyanufr** [comment]
run pytorch pre-commit tests

**Comment by andreyanufr** [comment]
run onnx pre-commit tests

**Comment by andreyanufr** [comment]
run openvino pre-commit tests

**Review by alexsu52 — APPROVED** [review]
LGTM

**Comment by andreyanufr** [comment]
run openvino pre-commit tests

**Comment by andreyanufr** [comment]
run tensorflow pre-commit tests

**Comment by andreyanufr** [comment]
run pylint pre-commit tests

**Review by AlexKoff88 — APPROVED** [review]

**Review by ljaljushkin — APPROVED** [review]

**Pull request merged**
