### PR TITLE
Switch to VOC2012 in eval mode for SSD models

### PR DESCRIPTION
**Pull request by pfinashx**

### CODE REVIEW

**Comment by pfinashx** [comment]
Jenkins please retry a build

**Comment by vshampor** [comment]
Jenkins please retry a build

**Comment by vshampor** [comment]
@pfinashx update the corresponding table entries in all `README.md` files as well.

**Comment by pfinashx** [comment]
> @pfinashx update the corresponding table entries in all `README.md` files as well.



> @pfinashx update the corresponding table entries in all `README.md` files as well.

Done

**Comment by vshampor** [comment]
Jenkins please retry a build

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by vshampor** [comment]
Jenkins please retry a build

**Review by vshampor — APPROVED** [review]

**Pull request merged**
