### PR TITLE
[PTQ][OV] Remove inplace = False workaround for previous OpenVino release

### PR DESCRIPTION
**Pull request by daniil-lyakhov**
### Changes

inplace = False workaround removed from the code

### Reason for changes

To insert all operation possible operation inplase therefore to safe more memory during quantization

### CODE REVIEW

**Review by alexsu52 — APPROVED** [review]
LGTM

**Comment by KodiaqQ** [comment]
Did the conformance test pass?

**Comment by daniil-lyakhov** [comment]
Workaround for minor OV bug described in ticked 113288 was added

**Comment by daniil-lyakhov** [comment]
Some models from DLBenchmark are failed due to inplace statistics couldn't work with outputs with specific dynamic shapes

**Pull request closed without merging**
