### PR TITLE
Update onnx, onnxruntime versions

### PR DESCRIPTION
**Pull request by kshpv**
### Changes

Update onnx == 1.17, onnxruntime == 1.19.2

### CODE REVIEW

**Comment by kshpv** [comment]
test_examples 565 - passed

**Comment by kshpv** [comment]
test_examples Windows 218 - in progress

**Comment by kshpv** [comment]
rerun test_examples Windows 225

**Comment by AlexanderDokuchaev** [comment]
windows/job/install_onnx/480
windows/job/precommit_onnx/456
windows/job/precommit_torch_cpu/490

**Review by AlexanderDokuchaev — APPROVED** [review]

**Pull request merged**
