### PR TITLE
Added condition to skip unsupported mask_rcnn models

### PR DESCRIPTION
**Pull request by pfinashx**
After Monday discussion, added condition to skip unsupported models

### CODE REVIEW

**Review by alexsu52 — CHANGES_REQUESTED** [review]
Please, provide e2e build results

**Comment by pfinashx** [comment]
> Please, provide e2e build results

Started build 178

**Comment by pfinashx** [comment]
Build finished - 
[e2e_tf_results.xlsx](https://github.com/openvinotoolkit/nncf/files/6777853/e2e_tf_results.xlsx)

**Comment by alexsu52** [comment]
> 
> 
> Build finished -
> [e2e_tf_results.xlsx](https://github.com/openvinotoolkit/nncf/files/6777853/e2e_tf_results.xlsx)

Please, provide a green build exclude mask_rcnn models

**Comment by pfinashx** [comment]
Jenkins please retry a build

**Comment by alexsu52** [comment]
Jenkins please retry a build

**Review by alexsu52 — APPROVED** [review]

**Pull request merged**
