### PR TITLE
Add functional test of ONNX PTQ of detection models

### PR DESCRIPTION
**Pull request by kshpv**
### Changes

- Add hardware fusing pattern for input preprocessing
- Add graph test for yolov2, tiny-yolov2. Currently, there are some issues with SSD models

      https://github.com/onnx/onnx/issues/4101
      https://github.com/onnx/onnx/issues/4102

### Reason for changes

Extend support of ONNX PTQ models

### Related tickets

83146

### Tests

As stated in the title

### CODE REVIEW

**Comment by kshpv** [comment]
I tried to test SSD-300 model from torchvision repo, the model was successfully quantized and onnx assumes that the model is correct, while onnxruntime can't infer the model with the following error: 

`INVALID_ARGUMENT : Non-zero status code returned while running Conv node. Name:'Conv_123' Status Message: Invalid input shape: {0,0}`

I propose to include for now only yolov2 and tiny-yolov2 and focus on the domain - semantic segmentation and then proceed with SSD

**Comment by kshpv** [comment]
Jenkins please retry a build

**Comment by KodiaqQ** [comment]
@kshpv, did we plan to add a sample for the detection models in this PR or not? How did the models were tested in terms of accuracy?

**Comment by kshpv** [comment]
> @kshpv, did we plan to add a sample for the detection models in this PR or not? How did the models were tested in terms of accuracy?

No, currently we only add functional support (by adding test which do quantization, but the dataset is dummy).
After that we will introduce a full sample with object detection models

**Review by KodiaqQ — APPROVED** [review]

**Review by vshampor — APPROVED** [review]

**Pull request merged**
