### PR TITLE
[PTQ] Disable MMAP

### PR DESCRIPTION
**Pull request by KodiaqQ**
### Changes

- Disabled MMAP

### Reason for changes

- Failures on Windows

### CODE REVIEW

**Comment by KodiaqQ** [comment]
run pylint pre-commit tests

**Comment by KodiaqQ** [comment]
run pytorch pre-commit tests

**Comment by KodiaqQ** [comment]
run onnx pre-commit tests

**Comment by KodiaqQ** [comment]
Windows pre-commit run - 91

**Review by alexsu52 — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
