### PR TITLE
[OV] Disable quantization of GRUSequence with linear_before_reset=True

### PR DESCRIPTION
**Pull request by l-bat**
### Changes

NNCF should not quantize GRU ops with linear_before_reset set to true, since oneDNN does not support it yet

### Reason for changes

To align with POT

### Related bug

https://github.com/openvinotoolkit/nncf/issues/2105

### Tests

Added `test_ignore_nodes_by_attribues` for OV backend

### CODE REVIEW

**Review by KodiaqQ — APPROVED** [review]

**Comment by l-bat** [comment]
run pylint pre-commit tests
run pytorch pre-commit tests
run tensorflow pre-commit tests
run openvino pre-commit tests
run onnx pre-commit tests

**Comment by KodiaqQ** [comment]
run pylint pre-commit tests
run pytorch pre-commit tests
run openvino pre-commit tests
run onnx pre-commit tests

**Comment by l-bat** [comment]
run tensorflow pre-commit tests

**Comment by l-bat** [comment]
run tensorflow pre-commit tests

**Comment by alexsu52** [comment]
run tensorflow pre-commit tests

**Pull request merged**
