### PR TITLE
Fix quantized values miss exact zero

### PR DESCRIPTION
**Pull request by daniil-lyakhov**
`tf.quantization.fake_quant_with_min_max_vars` sometimes returns small values on zero valued inputs due to arithmetic error. Updated export save exact zero value indexes and after saturation issue fix applied restore exact zeros on saved indexes

### CODE REVIEW

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by FyodorK** [comment]
Jenkins please stop all builds

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Review by evgeniya-egupova — APPROVED** [review]

**Comment by FyodorK** [comment]
Jenkins please stop all builds

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by FyodorK** [comment]
Jenkins please stop all builds

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by daniil-lyakhov** [comment]
Jenkins please retry a build

**Comment by daniil-lyakhov** [comment]
Jenkins please retry a build

**Review by alexsu52 — APPROVED** [review]

**Pull request merged**
