### PR TITLE
Add handling for unsupported TF feature (compression_lr_multiplier)

### PR DESCRIPTION
**Pull request by a-ignatyev**

### CODE REVIEW

**Comment by a-ignatyev** [comment]
Jenkins please retry a build

**Review by alexsu52 — APPROVED** [review]
Looks good to me.

**Comment by alexsu52** [comment]
Jenkins please retry a build

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by FyodorK** [comment]
Jenkins please retry a build

**Comment by a-ignatyev** [comment]
Jenkins please retry a build

**Comment by a-ignatyev** [comment]
Jenkins please retry a build

**Review by vshampor — APPROVED** [review]

**Pull request merged**
