### PR TITLE
Fix not renamed `weight_importance` attribute occurrences

### PR DESCRIPTION
**Pull request by mkaglins**
In this PR fixed configs and code occurrences of `weight_importance` param that was renamed to `filter_importance`.

Ticket - 59470

### CODE REVIEW

**Comment by mkaglins** [comment]
@evgeniya-egupova  Please, take a look.

**Comment by evgeniya-egupova** [comment]
There are new pruning+quantization configs in classification and obj det examples. Please fix them too.

**Comment by mkaglins** [comment]
Jenkins please retry a build

**Comment by mkaglins** [comment]
> There are new pruning+quantization configs in classification and obj det examples. Please fix them too.

Done.

**Review by evgeniya-egupova — APPROVED** [review]

**Pull request merged**
