### PR TITLE
Use find_spec instead of try-import-except to detect backends

### PR DESCRIPTION
**Pull request by vshampor**
#2060

### CODE REVIEW

**Review by KodiaqQ — APPROVED** [review]

**Comment by KodiaqQ** [comment]
Please, update the branch with https://github.com/openvinotoolkit/nncf/pull/2068

**Comment by vshampor** [comment]
run torch pre-commit tests

**Comment by vshampor** [comment]
run pytorch pre-commit tests

**Comment by vshampor** [comment]
run pytorch pre-commit tests

**Pull request merged**
