### PR TITLE
Remove requirements.txt

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
### Changes

Removed requirements.txt

### Reason for changes

- requirements.txt that install package is not expected as default behavior to install module in editable mode.
- editable mode is deprecated 
- requirements.txt not actual after pyproject.toml

### CODE REVIEW

**Review by alexsu52 — APPROVED** [review]
LGTM

**Review by alexsu52 — COMMENTED** [review]
@AlexanderDokuchaev, @MaximProshin, please, estimate impact to 3rd party components and validation.

**Comment by MaximProshin** [comment]
@AlexanderDokuchaev , please run install and examples tests or share links if you did it already.

**Comment by AlexanderDokuchaev** [comment]
@MaximProshin 
https://github.com/openvinotoolkit/nncf/actions/runs/12119723846 - install
https://github.com/openvinotoolkit/nncf/actions/runs/12120781143 - examples

**Pull request merged**
