### PR TITLE
[PTQ] Update MinMax logic for unified embeddings

### PR DESCRIPTION
**Pull request by KodiaqQ**
### Changes

- Updated MinMax logic to work with quantizers for embedding that may be unified

### Reason for changes

- Bugfix

### Related tickets

- 119561

### Tests

- Updated graph tests

image

### CODE REVIEW

**Comment by KodiaqQ** [comment]
run tensorflow pre-commit tests

**Comment by KodiaqQ** [comment]
run tensorflow pre-commit tests

**Review by alexsu52 — APPROVED** [review]
LGTM

**Comment by KodiaqQ** [comment]
run tensorflow pre-commit tests

**Pull request merged**
