### PR TITLE
[TF] Migrate to tf2.4

### PR DESCRIPTION
**Pull request by evgeniya-egupova**

### CODE REVIEW

**Comment by evgeniya-egupova** [comment]
Jenkins please retry a build

**Comment by evgeniya-egupova** [comment]
Jenkins please retry a build

**Comment by evgeniya-egupova** [comment]
Jenkins please retry a build

**Review by alexsu52 — APPROVED** [review]

**Comment by zmaslova** [comment]
Jenkins please retry a build

**Comment by evgeniya-egupova** [comment]
Jenkins please retry a build

**Comment by zmaslova** [comment]
Jenkins please retry a build

**Pull request merged**
