### PR TITLE
Updated reference for 2023.2.0-12979-04c766e9f17

### PR DESCRIPTION
**Pull request by ljaljushkin**
- [ ] pass nncf + openvino-nightly tests - build#7

### CODE REVIEW

**Comment by ljaljushkin** [comment]
References from the latest update (https://github.com/openvinotoolkit/nncf/pull/2203) doesn't pass CI with fresher OV commit 04c766e9f17

**Comment by ljaljushkin** [comment]
run pylint pre-commit tests

**Comment by ljaljushkin** [comment]
run pylint pre-commit tests

**Review by alexsu52 — APPROVED** [review]
LGTM

**Pull request merged**
