### PR TITLE
[ReleaseV250] Introduced the drop_type parameter to the quantize_with_accuracy_control function

### PR DESCRIPTION
**Pull request by alexsu52**
### Changes

https://github.com/openvinotoolkit/nncf/pull/1758

### CODE REVIEW

**Comment by MaximProshin** [comment]
approved for merging to the release branch

**Review by KodiaqQ — APPROVED** [review]

**Comment by alexsu52** [comment]
run openvino pre-commit tests

**Comment by alexsu52** [comment]
run openvino pre-commit tests

**Comment by alexsu52** [comment]
run tensorflow pre-commit tests

**Comment by alexsu52** [comment]
run pytorch pre-commit tests

**Comment by alexsu52** [comment]
run pytorch pre-commit tests

**Pull request merged**
