### PR TITLE
ONNX examples version update

### PR DESCRIPTION
**Pull request by kshpv**
### Changes

Update version onnx==1.17.0 for all examples where the version of onnx is specified

### CODE REVIEW

**Comment by MaximProshin** [comment]
@kshpv , please run Trivy scan on your PR.

**Comment by kshpv** [comment]
Windows:
251 (yolo) - passed
253 (llm) - in progress
Linux:
582 (yolo) - passed
594 (llm) - in progress

**Comment by kshpv** [comment]
new run
Windows:
255 (llm) - in progress

**Comment by AlexanderDokuchaev** [comment]
windows/job/test-examples/258

**Review by AlexanderDokuchaev — APPROVED** [review]

**Pull request merged**
