### PR TITLE
[PTQ][OV] Support Depthwise, Group convolutions

### PR DESCRIPTION
**Pull request by l-bat**
### Changes

* Add `OVDepthwiseConvolutionMetatype` as a subtype of `OVGroupConvolutionMetatype`

### Reason for changes

* To correctly quantize depthwise and group convolutions.

### Related tickets

* 101928

### Tests

* Added `DepthwiseConvModel` synthetic model for tests

### CODE REVIEW

**Comment by daniil-lyakhov** [comment]
There are no problems to rebase #1471 on top of in 👍

**Review by kshpv — APPROVED** [review]

**Review by KodiaqQ — APPROVED** [review]

**Review by alexsu52 — APPROVED** [review]
LGTM

**Review by andrey-churkin — APPROVED** [review]

**Review by daniil-lyakhov — APPROVED** [review]

**Comment by l-bat** [comment]
run tensorflow pre-commit tests

**Comment by l-bat** [comment]
run pytorch pre-commit tests

**Pull request merged**
