### PR TITLE
Dispatch bfloat along with the rest of the types for the kernels

### PR DESCRIPTION
**Pull request by vshampor**
### Changes
As stated in the title

### Reason for changes
Otherwise the autocast to BF16 does not work with quantization.

### Related tickets
N/A

### Tests
test_external_autocast on CPU-only hosts

### CODE REVIEW

**Comment by vshampor** [comment]
Quantization function benchmark results TBA

**Comment by vshampor** [comment]
CUDA kernels measured to have an average of 3.4% perf boost as a result of this change, CPU kernels have a 0.89% perf degradation. Safe to say that the performance is largely unchanged.

**Review by alexsu52 — COMMENTED** [review]
Thanks for the contribution. Could you provide sota_eval test results?

**Comment by vshampor** [comment]
sota_pytorch_eval run 411 shows no significant changes when compared to the nightly run from develop.

**Review by alexsu52 — APPROVED** [review]
LGTM

**Comment by vshampor** [comment]
run pytorch pre-commit tests

**Pull request merged**
