### PR TITLE
[PTQ] Update F-/BC with the dynamism

### PR DESCRIPTION
**Pull request by KodiaqQ**
### Changes

- Fixed the ModelTransformer behavior for BiasCorrection algorithms
- Fixed (Full)BiasCorrection algorithm

### Reason for changes

- Detection models support

### Related tickets

- 103935

### CODE REVIEW

**Review by andrey-churkin — APPROVED** [review]

**Review by alexsu52 — APPROVED** [review]
LGTM

**Review by l-bat — APPROVED** [review]

**Comment by alexsu52** [comment]
run pylint pre-commit tests

**Comment by KodiaqQ** [comment]
run pylint pre-commit tests

**Comment by KodiaqQ** [comment]
run onnx pre-commit tests

**Pull request merged**
